export enum InputKeys {
  "supportingProps" = "supportingProps",
  "utils" = "supportingProps.utils",
  "variables" = "supportingProps.variables",
  "database" = "supportingProps.database",
  "mutation" = "mutation",
  "formDefination" = "formDefination",
  "callbacks" = "callbacks",
  "independentCallbacks" = "callbacks.independent",
  "dependentCallbacks" = "callbacks.dependent",
  "onInitialRender" = "onInit",
  "domManipulatiion" = "dom_manipulation",
  "feedback" = "feedback",
  "layout" = "layout",
  "styleHint" = "styleHint",
  "validate" = "validate",
  "fieldDefinations" = "fieldDefinations",
  "multiStep" = "multiStep",
  "type" = "type",
}
